/* ===========================================================================
   Dog Walking Calculator — DATASET AND RULES
   ---------------------------------------------------------------------------
   Pure data. No logic, no DOM. engine.js is the only module that imports this.

   PROVENANCE
   Breeds are derived from this site's own Breed Matcher dataset
   (public/breed-matcher/index.html), then cross-checked breed by breed against:
     - The Royal Kennel Club's per-breed "Exercise" tier
       ("Up to 30 minutes per day" / "Up to 1 hour per day" /
        "Between 1-2 hours per day" / "More than 2 hours per day")
     - PDSA's per-breed "Minimum exercise (per day)" fact box
       (a three-value ladder: 30 minutes / 1 hour / 2 hours)
   Note the two are NOT the same quantity: PDSA publishes a MINIMUM, the RKC
   publishes an upper-ish band. Each breed's `source` field records what was
   actually found.

   BAND ASSIGNMENT RULE
   The band follows the published evidence, EXCEPT where a documented physical
   constraint makes that figure unsafe as a target - a flat-faced (brachycephalic)
   airway, or a giant frame carrying joint and bloat risk. Those breeds are banded
   down a step and the `note` says so explicitly. There are no silent averages.

   WHAT IS OURS, NOT SOURCED
   The minute ranges below are ours. The RKC publishes tiers and PDSA publishes
   minimums; neither publishes these four ranges. Band edges are placed on the
   published landmarks (30, 60 via the 45-75 band, and 120) so each tier maps
   cleanly. See RULES for the other two editorial decisions.

   Generated 2026-07-21 from the research bundle; safe to hand-edit afterwards.
   Adding a breed is additive: append a row, then run the test harness, which
   fails loudly on a duplicate slug, a clashing alias or an unknown band.
   =========================================================================== */

/** Display order for the energy-level cards. */
export const BAND_ORDER = ['low', 'moderate', 'high', 'working'];

export const BANDS = {
  low: {
    id: "low",
    label: "Light",
    minMinutes: 30,
    maxMinutes: 45,
    descriptor: "A dog who takes life gently",
    summary: "Short, unhurried walks. Sniffing matters far more than distance.",
  },
  moderate: {
    id: "moderate",
    label: "Steady",
    minMinutes: 45,
    maxMinutes: 75,
    descriptor: "A steady, everyday sort of dog",
    summary: "A decent walk or two a day. They will let you know if one gets missed.",
  },
  high: {
    id: "high",
    label: "High",
    minMinutes: 75,
    maxMinutes: 120,
    descriptor: "A dog with real drive",
    summary: "Needs proper exercise and something to think about, not a lap of the block.",
  },
  working: {
    id: "working",
    label: "Very high",
    minMinutes: 120,
    maxMinutes: 180,
    descriptor: "A dog bred to work all day",
    summary: "Two hours or more, most days. Distance alone will not settle them.",
  },
};

/* ===========================================================================
   RULES — every number the engine uses
   ===========================================================================
   Three of these are OUR editorial judgement rather than published guidance,
   and the on-page copy says so. Do not quietly change one without changing the
   copy in copy.js to match.
   =========================================================================== */
export const RULES = {
  puppy: {
    /* The Royal Kennel Club's rule of thumb: "five minutes of formal exercise
       per month of age (up to twice a day) until the puppy is fully grown".
       SOURCED. Note PDSA disagrees with the rule itself - see copy.js.
       It is a budget for FORMAL/lead exercise only; free play is separate and
       puppies self-limit. */
    minutesPerMonthOfAge: 5,
    sessionsPerDay: 2,

    minMonths: 2,
    maxMonths: 18,

    /* NOT SOURCED - ours. No authority publishes a cap. Without it the rule
       overshoots the adult figure for a small breed from about four months
       (5 x 4 x 2 = 40 min against a 30-45 min adult band). */
    capAtAdultMax: true,
  },

  senior: {
    /* NOT SOURCED - ours. No UK or international authority publishes any
       percentage or fraction for reducing an older dog's exercise. PDSA says
       only "a little less"; Blue Cross's "2 x 30 min rather than an hour" is a
       REDISTRIBUTION at unchanged volume, not a cut. 0.8 is our reading of "a
       little less". The well-supported part is the split, not the reduction. */
    factor: 0.8,
    sessionsPerDay: 3,
    minimumMinutes: 15,
  },

  adult: {
    sessionsPerDay: 2,
  },

  search: {
    maxSuggestions: 8,
    /* Below this length a typo correction is meaningless, so we do not attempt
       one - "lab" is not a misspelling of anything. */
    minFuzzyLength: 4,
  },

  rounding: {
    /* Users read "45 minutes" more naturally than "43 minutes". */
    step: 5,
  },
};

/* ===========================================================================
   BREEDS (97)
   ---------------------------------------------------------------------------
   slug            stable id, used for ?breed= deep links. Never reuse or rename.
   band            low | moderate | high | working  (see BANDS)
   size            1 toy .. 5 giant, carried over from the Breed Matcher
   aliases         lowercase; what a real UK owner might type. Must be globally
                   unique and must never equal another breed's real name.
                   The engine also handles plurals, filler words ("pug dog",
                   "lab puppy", "collie cross"), punctuation, accents and
                   single-letter typos, so those do NOT need alias entries.
   brachycephalic  flat-faced: raises the airway/heat caution
   giantGrowth     slow-maturing: raises the longer-puppy-restriction caution
   sighthound      sprinter rather than distance dog
   source          what the RKC and PDSA actually publish for this breed
   note            editorial guidance shown to no one by default; kept as the
                   audit trail for why the band is what it is
   =========================================================================== */
export const BREEDS = [
  { slug: "afghan-hound", name: "Afghan Hound", group: "Hound", size: 4, band: "working",
    aliases: ["afghan","afgan hound","afgan","afghan houd"],
    brachycephalic: false, giantGrowth: false, sighthound: true,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Purina’s one to two hours is the outlier here; RKC and PDSA both say two hours or more and we have followed them. The requirement is safe free galloping space for a sighthound rather than obedience-style work, and the coat needs daily attention after muddy walks." },
  { slug: "airedale-terrier", name: "Airedale Terrier", group: "Terrier", size: 4, band: "high",
    aliases: ["airedale","aredale","king of terriers","airdale terrier","waterside terrier"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: no page",
    note: "We have banded above the RKC tier: Purina gives one to two hours and this is the largest terrier with genuine working and service history, so the coarse RKC band looks like an under-statement. Bored Airedales are destructive, so count the mental work alongside the minutes." },
  { slug: "akita", name: "Akita", group: "Utility", size: 5, band: "working",
    aliases: ["japanese akita","akita inu","american akita","great japanese dog","akitas"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "This record covers the Akita in the broad sense. The Kennel Club registers the Akita and the Japanese Akita Inu as separate breeds; the guidance here applies reasonably to both." },
  { slug: "alaskan-malamute", name: "Alaskan Malamute", group: "Working", size: 5, band: "working",
    aliases: ["malamute","mally","mallie","alaskan malamut","malemute","alaskan malmute"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Bred for hours of load-hauling endurance, and both authorities put it in the two-hour-plus tier. Heavy double coat and real bulk mean heat intolerance, and the breed’s hip dysplasia and chondrodysplasia risk means building distance gradually." },
  { slug: "australian-shepherd", name: "Australian Shepherd", group: "Pastoral", size: 3, band: "working",
    aliases: ["aussie","aussie shepherd","australian shepard","aus shepherd","australian sheepdog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Three sources agree on 120 minutes or more and all stress that walking alone is not enough — agility, herding or scent work has to sit alongside it. Carries the MDR1 mutation, and merle-to-merle lines bring deafness and blindness risk." },
  { slug: "basenji", name: "Basenji", group: "Hound", size: 2, band: "moderate",
    aliases: ["basengi","basenji dog","african barkless dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour (fact box) / 60-90 minutes (body copy)",
    note: "Banded at the top of moderate: the fact boxes say 60 minutes but PDSA’s prose stretches to 90 and Purina says more if you can offer it. A notorious escape artist with very high prey drive and poor road sense, so secure space only, with mental work alongside." },
  { slug: "basset-hound", name: "Basset Hound", group: "Hound", size: 3, band: "moderate",
    aliases: ["basset","bassett hound","bassett","basset hound dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "PDSA warns explicitly not to be fooled by the laid-back look — all three sources give a full hour. Heavy body on short legs means joint, back and ear problems plus a strong obesity tendency, so favour steady sniffy walking over speed or jumping." },
  { slug: "beagle", name: "Beagle", group: "Hound", size: 3, band: "high",
    aliases: ["beagel","beagal","beagle hound"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour (fact box) / 90 minutes (body copy)",
    note: "The fact boxes say an hour but PDSA’s own prose asks for an hour and a half and Purina says one to two, so we have banded up. A relentless nose-led scent hound with near-zero recall on a trail, and strongly prone to obesity if under-walked." },
  { slug: "bearded-collie", name: "Bearded Collie", group: "Pastoral", size: 4, band: "high",
    aliases: ["beardie","beardy"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Both authorities publish an hour but Purina adds \"ideally much more\", so treat the hour as a floor rather than a target — an active Beardie will want 90 minutes plus of off-lead running. The long shaggy coat collects mud and burrs and limits it in heat." },
  { slug: "bedlington-terrier", name: "Bedlington Terrier", group: "Terrier", size: 3, band: "moderate",
    aliases: ["bedlington","bedlinton terrier","rothbury terrier","lamb dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "All three sources agree on an hour with room for more. The sighthound-influenced build gives real sprinting speed and chase drive, so short bursts of secure free running suit it better than long plodding; copper toxicosis is the breed-defining health screen." },
  { slug: "belgian-malinois", name: "Belgian Malinois", group: "Pastoral", size: 4, band: "working",
    aliases: ["malinois","mal","malinios","belgian shepherd","belgian shepherd dog","belgium malinois"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: no page",
    note: "The clearest working-band entry in the set: RKC’s top tier plus Purina explicitly requiring some form of work or sport on top. A pet-home Malinois given only walks reliably develops serious behavioural problems." },
  { slug: "bernese-mountain-dog", name: "Bernese Mountain Dog", group: "Working", size: 5, band: "moderate",
    aliases: ["bernese","berner","bmd","bernese mountain","burmese mountain dog","bernese mountain dogs"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "The published hour sits at the top of this band. Giant, slow-maturing and heavily coated: restrict a puppy hard until around 18 months and expect real heat intolerance in summer." },
  { slug: "bichon-frise", name: "Bichon Frise", group: "Utility", size: 1, band: "low",
    aliases: ["bichon","bishon frise","bichon fries","bichon frize","bishon"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "All three sources agree on 30 minutes minimum plus enrichment, which genuinely meets the requirement even though a bouncy Bichon will happily take more. Worth noting the RKC files this breed under Toy, not Utility as the base dataset does." },
  { slug: "bloodhound", name: "Bloodhound", group: "Hound", size: 5, band: "working",
    aliases: ["blood hound","bloodhound dog","sleuth hound"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Unanimous at two hours plus, and both PDSA and Purina insist the time be scent-led trailing rather than plain walking. Giant, deep-chested and slow to mature, so no hard work around meals and restricted puppy exercise while the joints develop." },
  { slug: "border-collie", name: "Border Collie", group: "Pastoral", size: 3, band: "working",
    aliases: ["collie","bc","boarder collie","border coli","sheepdog","working sheepdog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Two named authorities agree on 120 minutes or more, and both insist the walking is paired with real thinking work or the dog self-employs on traffic, joggers and bikes. Watch for Collie Eye Anomaly, hip dysplasia and the MDR1 drug sensitivity in some lines." },
  { slug: "border-terrier", name: "Border Terrier", group: "Terrier", size: 2, band: "moderate",
    aliases: ["boarder terrier","border terrier dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "All three named sources agree on roughly an hour as the floor with plenty of capacity for more. A hardy, low-drama walking companion whose practical limiter is recall on a scent rather than stamina." },
  { slug: "boston-terrier", name: "Boston Terrier", group: "Utility", size: 2, band: "moderate",
    aliases: ["boston","bostons","boston terriers"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "A published hour, best split and kept out of midday sun. Flat-faced though less extremely than a Frenchie or Bulldog, so heat-sensitive, and the prominent eyes are vulnerable to injury." },
  { slug: "boxer", name: "Boxer", group: "Working", size: 4, band: "high",
    aliases: ["boxer dog","german boxer","boxr"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "The published tier is two hours plus, but a flat-faced airway sets the practical ceiling, so we band it down a step. A fit Boxer will happily do more in cool weather; the shape of the exercise matters more than the total." },
  { slug: "brittany", name: "Brittany", group: "Gundog", size: 3, band: "working",
    aliases: ["brittany spaniel","britany","brittanys","french brittany"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: no page",
    note: "A full pointing breed in a medium-sized body, so size alone badly under-predicts it — RKC and Purina both say two hours or more. Needs physical and mental work together or it turns destructive." },
  { slug: "bull-terrier", name: "Bull Terrier", group: "Terrier", size: 3, band: "moderate",
    aliases: ["english bull terrier","ebt","bull terrier english","egg head dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Sources conflict — both authorities say an hour while Purina says two — so we have followed RKC and PDSA, though a fit adult will comfortably take more. Powerfully built and heat-limited in summer, and prone to deafness and kidney disease." },
  { slug: "bulldog", name: "Bulldog", group: "Utility", size: 3, band: "moderate",
    aliases: ["british bulldog","english bulldog","bull dog"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "The need is real — both authorities publish up to an hour — but the intensity must be low. Severely flat-faced with a heavy front, so heat-limited and prone to hip and elbow dysplasia; never a jogging or long-hike dog." },
  { slug: "bullmastiff", name: "Bullmastiff", group: "Working", size: 5, band: "moderate",
    aliases: ["bull mastiff","bullmastif","bullmastiffs"],
    brachycephalic: true, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "We deliberately band this one below what the Royal Kennel Club and PDSA publish. A 50kg-plus flat-faced mastiff carries airway, joint and bloat risk together, and two hours a day is not a safe target for most. Build up slowly, keep it cool, and let the dog set the pace." },
  { slug: "cairn-terrier", name: "Cairn Terrier", group: "Terrier", size: 2, band: "moderate",
    aliases: ["cairn","carin terrier","cairne terrier","toto dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Three sources agree on an hour minimum. PDSA specifically flags the hunting instinct — once on a scent they are hard to recall — so sniffing walks in secure places are worth more here than covering ground." },
  { slug: "cane-corso", name: "Cane Corso", group: "Working", size: 5, band: "working",
    aliases: ["corso","cane corso italiano","italian mastiff","kane korso","cane corsa","canecorso"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: not Kennel Club recognised in the UK; PDSA: 2 hours",
    note: "No Kennel Club tier exists because the breed is not RKC recognised, but PDSA publishes two hours and this is a powerful guardian needing structured training alongside the walking. Hip and elbow dysplasia plus bloat risk mean no hard work before about 18 months or within an hour of a meal." },
  { slug: "cavachon", name: "Cavachon", group: "Cross", size: 1, band: "moderate",
    aliases: ["cava chon","cavalier bichon cross","bichon cavalier cross","cavachons"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: not recognised (Cavalier x Bichon Frise cross); PDSA: no page",
    note: "The two parents differ by a full published tier (Cavalier an hour, Bichon Frise 30 minutes) and secondary UK sources go as low as 30 to 45 minutes; we follow Purina’s cross-specific hour, with 45 minutes reasonable for a quieter or older dog. Cavalier parentage brings heart and syringomyelia risk and a slightly shortened muzzle." },
  { slug: "cavalier-king-charles-spaniel", name: "Cavalier King Charles Spaniel", group: "Toy", size: 2, band: "moderate",
    aliases: ["cavalier","cav","cavvy","ckcs","cavalier spaniel","king charles cavalier","cavalier king charles","king charles"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Three sources agree on about an hour, best split into two walks. Mildly flat-faced and very prone to mitral valve disease and syringomyelia, so exercise tolerance often drops sharply from middle age — treat new coughing or fatigue as a vet matter, not unfitness." },
  { slug: "cavapoo", name: "Cavapoo", group: "Cross", size: 1, band: "moderate",
    aliases: ["cavoodle","cavadoodle","cava poo","cavalier poodle cross","cavapoos"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: not recognised (Cavalier x Poodle cross); PDSA: no page",
    note: "Unusually consistent evidence at about an hour a day, split into two or three shorter walks. Cavalier parentage carries mitral valve disease and syringomyelia risk plus a slightly shortened muzzle, so avoid heat and treat new exercise intolerance as a vet issue rather than unfitness." },
  { slug: "chesapeake-bay-retriever", name: "Chesapeake Bay Retriever", group: "Gundog", size: 4, band: "working",
    aliases: ["chessie","chessies","chesapeake","chesapeake retriever","chessy"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: no page",
    note: "RKC and Purina UK both ask for two or more hours across varied terrain, ideally including swimming and water retrieves. The harshest-weather retriever of the group and the least forgiving of a light day." },
  { slug: "chihuahua", name: "Chihuahua", group: "Toy", size: 1, band: "low",
    aliases: ["chiwawa","chihuaua","chiuaua","chi","teacup chihuahua","long haired chihuahua","chihuaha"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "All three sources converge on about 30 minutes, ideally split into two short walks with play and training on top. Fragile, prone to luxating patellas and tracheal collapse — use a harness, never a collar — and genuinely cold-sensitive in British winters." },
  { slug: "chow-chow", name: "Chow Chow", group: "Utility", size: 4, band: "moderate",
    aliases: ["chow","chowchow","chow chows","chow dog"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "RKC, PDSA and Purina all publish about an hour, which is more than the breed’s aloof reputation implies. The dense double coat and slightly shortened muzzle make Chows badly heat-intolerant, and the straight-hocked rear suits steady walking over sustained running." },
  { slug: "cockapoo", name: "Cockapoo", group: "Cross", size: 2, band: "moderate",
    aliases: ["cockerpoo","cocker poo","cockapoodle","cockerpoodle","spoodle","cockapoos","cockerpoos"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: not recognised (Cocker x Poodle cross); PDSA: no page",
    note: "Every published parent figure — RKC Cocker, RKC Miniature and Toy Poodle, PDSA Cocker — lands at up to an hour, and Purina rates the cross only three out of five for exercise need. Parentage matters more than the label: a working-cocker-bred Cockapoo behaves far closer to the demanding band." },
  { slug: "dalmatian", name: "Dalmatian", group: "Utility", size: 4, band: "working",
    aliases: ["dalmation","dally","dalmatians","dalmatin","spotty dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "A bred-for-endurance coaching dog: two hours plus of genuine running, come rain or shine, and Purina warns an under-exercised Dalmatian becomes hyperactive and hard to live with. Watch for congenital deafness, and keep water available on long walks because of the urate stone risk." },
  { slug: "dobermann", name: "Dobermann", group: "Working", size: 4, band: "working",
    aliases: ["doberman","dobie","doby","dobe","doberman pinscher","dobermann pinscher","dobberman"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "A genuine two-hour breed that needs a job as well as a walk. Deep-chested, so avoid hard work within an hour of feeding, and be alert to dilated cardiomyopathy reducing exercise tolerance with age." },
  { slug: "dogue-de-bordeaux", name: "Dogue de Bordeaux", group: "Working", size: 5, band: "moderate",
    aliases: ["ddb","french mastiff","dogue","dog de bordeaux","bordeaux mastiff","doggy de bordeaux"],
    brachycephalic: true, giantGrowth: true, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "A minimum of an hour, happily taken as several short walks with play and training on top. Short-muzzled and very heavy, so heat-limited; a Category Three breed with skin-fold problems and hip and elbow dysplasia." },
  { slug: "english-cocker-spaniel", name: "English Cocker Spaniel", group: "Gundog", size: 3, band: "moderate",
    aliases: ["cocker","cocker spaniel","show cocker","english cocker","cockerspaniel"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "The only gundog here that the RKC rates under two hours, and PDSA agrees at one hour. Show-bred cockers genuinely do settle on an hour; a working-line dog is a different animal and belongs a band higher." },
  { slug: "english-springer-spaniel", name: "English Springer Spaniel", group: "Gundog", size: 3, band: "working",
    aliases: ["springer","springer spaniel","english springer","springers"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "PDSA is unusually blunt about needing an owner prepared to give over two hours a day, and Purina UK talks in terms of several hours. Distance is not the point — flushing, hunting and scent games are, or the dog will find its own job." },
  { slug: "flat-coated-retriever", name: "Flat-Coated Retriever", group: "Gundog", size: 4, band: "working",
    aliases: ["flatcoat","flat coat","flattie","flat coated retriever"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: no page",
    note: "RKC and Purina UK independently settle on two hours as the bare minimum. Famously slow to grow up mentally, so sustained brain work matters; the breed’s high cancer rate and sub-ten-year lifespan are worth bearing in mind for older dogs." },
  { slug: "french-bulldog", name: "French Bulldog", group: "Utility", size: 2, band: "moderate",
    aliases: ["frenchie","frenchy","french bull dog","french bulldogs","frenchie dog"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Both authorities publish about an hour, so a Frenchie is not a 30-minute dog — but the hour must arrive as several short, gentle walks and be cut back above roughly 20C. Breathing is compromised and they overheat fast." },
  { slug: "german-shepherd", name: "German Shepherd", group: "Pastoral", size: 4, band: "working",
    aliases: ["gsd","alsatian","alsation","german shepard","german sheperd","german shepherd dog","shepherd"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "RKC says more than two hours and PDSA sets a two-hour minimum, best spread across the day rather than taken in one block. High breed incidence of hip and elbow dysplasia plus degenerative myelopathy means strict puppy restriction and low-impact adult work on soft ground." },
  { slug: "german-shorthaired-pointer", name: "German Shorthaired Pointer", group: "Gundog", size: 4, band: "working",
    aliases: ["gsp","german pointer","german shorthair","shorthaired pointer","german short haired pointer","gsps"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "PDSA’s umbrella German Pointer page says over two hours ideally, matching RKC and Purina. Intensely scent-driven, so scent games count as real work; deep-chested for bloat risk, and it will keep going long past sensible in heat." },
  { slug: "giant-schnauzer", name: "Giant Schnauzer", group: "Working", size: 4, band: "working",
    aliases: ["riesenschnauzer","giant snauzer","giant schnouzer","giant shnauzer","schnauzer giant"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "A real guard and search-and-rescue working breed: two hours plus, with genuine problem-solving work alongside. Deep-chested with bloat risk and prone to hip dysplasia, so avoid exertion around meals and build up gradually." },
  { slug: "golden-retriever", name: "Golden Retriever", group: "Gundog", size: 4, band: "working",
    aliases: ["golden","goldie","goldy","golden retreiver","golden ret"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "PDSA asks for a minimum of two hours of good exercise spread across the day, which sits right at the top of this band. A slow-maturing large breed, so puppy work must be restricted and adult work kept off hard surfaces." },
  { slug: "goldendoodle", name: "Goldendoodle", group: "Cross", size: 4, band: "high",
    aliases: ["golden doodle","groodle","goldendoodles","golden poodle cross"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: not recognised (Golden Retriever x Poodle cross); PDSA: no page",
    note: "A cross, so it varies with the poodle size and the parent lines. Both parent breeds sit in the top published tier, so budget towards the upper end and expect a dog that needs a job." },
  { slug: "great-dane", name: "Great Dane", group: "Working", size: 5, band: "high",
    aliases: ["dane","great dain","german mastiff","grate dane"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Both authorities publish two hours a day, and the \"lazy giant\" idea is a myth. We still band a step below that: a giant frame brings joint and bloat risk, and steady low-impact work beats volume. Never exercise around mealtimes." },
  { slug: "greyhound", name: "Greyhound", group: "Hound", size: 4, band: "moderate",
    aliases: ["grey hound","greyhond","ex-racer","retired greyhound"],
    brachycephalic: false, giantGrowth: true, sighthound: true,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Banded at the lower end because Purina suggests two 20-minute runs will usually do, against the authorities’ hour. The classic sprint-not-distance sighthound: two short fast runs beat a long march, and chase drive makes off-lead work unsafe outside a secure field." },
  { slug: "havanese", name: "Havanese", group: "Toy", size: 1, band: "low",
    aliases: ["havenese","havanase","havana silk dog","hav"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "About 30 minutes, comfortably topped up with indoor play and training. Robust for a toy breed by PDSA’s own account, but a velcro companion prone to separation distress, and the long silky coat makes wet walks costly." },
  { slug: "hungarian-vizsla", name: "Hungarian Vizsla", group: "Gundog", size: 4, band: "working",
    aliases: ["vizsla","vizla","viszla","vizslas","hungarian pointer","velcro dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "All three sources agree on two hours minimum with secure off-lead running plus training on top — a true hunt-point-retrieve dog that needs a job, not just mileage. Very poor tolerance of being left, and a thin single coat that chills quickly in wet British weather." },
  { slug: "irish-setter", name: "Irish Setter", group: "Gundog", size: 4, band: "working",
    aliases: ["red setter","irish red setter","setter","irish setters"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Developed to quarter ground all day, and all three sources ask for two hours plus with genuine free running. Recall stays unreliable well past two years, so secure-space galloping is worth more than lead distance." },
  { slug: "irish-wolfhound", name: "Irish Wolfhound", group: "Hound", size: 5, band: "working",
    aliases: ["wolfhound","irish wolf hound","wolf hound","irish wolfhoud"],
    brachycephalic: false, giantGrowth: true, sighthound: true,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "All three sources put the adult at two hours or more, though the driver is free galloping and sniffing rather than a job. A three-year growth period and a sub-ten-year lifespan mean puppies and adolescents must be deliberately under-exercised — heavy walks for a young Wolfhound do real harm." },
  { slug: "italian-greyhound", name: "Italian Greyhound", group: "Toy", size: 1, band: "moderate",
    aliases: ["iggy","iggies","ig","italian grayhound","mini greyhound","miniature greyhound"],
    brachycephalic: false, giantGrowth: false, sighthound: true,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Three sources agree on about an hour — the highest figure in the Toy group and well above the 30-minute toy norm. A genuine sighthound wanting secure-field sprints rather than distance, with very fine leg bones that fracture easily and a thin coat for British winters." },
  { slug: "jack-russell-terrier", name: "Jack Russell Terrier", group: "Terrier", size: 2, band: "high",
    aliases: ["jrt","jack russell","jack russel","russell terrier","jack russell terrier dog","jackrussell"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Small, but a genuine working terrier with the drive to match. The published tier is an hour; most will take considerably more, and scent and digging games settle them in a way distance alone does not." },
  { slug: "japanese-shiba-inu", name: "Japanese Shiba Inu", group: "Utility", size: 3, band: "moderate",
    aliases: ["shiba","shiba inu","shiba inus","shibe","japanese shiba"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: no page",
    note: "PDSA has no Shiba page, so the RKC hour plus Purina are the evidence and both land at about 60 minutes with training on top. A primitive spitz with very high prey drive and notoriously unreliable recall, so most of that hour realistically needs a long line or a secure area." },
  { slug: "king-charles-spaniel", name: "King Charles Spaniel", group: "Toy", size: 1, band: "low",
    aliases: ["english toy spaniel","kc spaniel","toy spaniel"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: no page",
    note: "Constantly confused with the Cavalier but markedly flatter-faced and more sedentary; where RKC (30 minutes) and Purina (an hour) disagree we follow the RKC. A vulnerable native breed, flat-faced and therefore heat-limited." },
  { slug: "labradoodle", name: "Labradoodle", group: "Cross", size: 4, band: "high",
    aliases: ["doodle","labra doodle","labradoodles","lab poodle cross","australian labradoodle","labrapoodle"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: not recognised (Labrador x Poodle cross); PDSA: no page",
    note: "A cross, so it varies with the poodle size and the parent lines. Budget towards the upper end if either parent came from working stock." },
  { slug: "labrador-retriever", name: "Labrador Retriever", group: "Gundog", size: 4, band: "working",
    aliases: ["lab","labs","labrador","black lab","yellow lab","chocolate lab","labradore","labrador retreiver"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: variable (see above)",
    note: "The Royal Kennel Club puts the Labrador in its top tier and PDSA declines to give a single figure. Keep the work steady and low-impact rather than repetitive ball-launching: this breed combines hip and elbow dysplasia risk with a real tendency to gain weight." },
  { slug: "leonberger", name: "Leonberger", group: "Working", size: 5, band: "high",
    aliases: ["leonburger","leo","leonberg","leonberger dog","lionberger"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Published guidance is two hours plus. We band a step below on giant-growth and joint grounds. This is a slow-maturing breed, so the careful puppy period runs well past a year." },
  { slug: "lhasa-apso", name: "Lhasa Apso", group: "Utility", size: 2, band: "moderate",
    aliases: ["lhasa","lasa apso","lhaso apso","lhasa apso dog","lasso apso"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Purina says 30 minutes, RKC and PDSA say up to an hour; we follow the two UK authorities while accepting the lower end for an older dog. The long coat traps heat, so summer walks want shortening." },
  { slug: "lurcher", name: "Lurcher", group: "Hound (cross)", size: 4, band: "moderate",
    aliases: ["sighthound cross","greyhound cross","whippet cross"],
    brachycephalic: false, giantGrowth: false, sighthound: true,
    source: "Not a Kennel Club breed; banded alongside the Greyhound and Whippet (RKC: Up to 1 hour per day; PDSA: 1 hour)",
    note: "A sighthound crossed with something else, so it varies, but most settle on a similar routine to a Greyhound: a couple of steady walks plus a safe chance to really run. One of the most commonly owned types in the UK and a staple of rescue." },
  { slug: "maltese", name: "Maltese", group: "Toy", size: 1, band: "low",
    aliases: ["malteser","maltease","malt"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "All three sources agree on 30 minutes and Purina rates exercise needs at two out of five. The long white single coat mats and stains easily, so muddy or wet walks carry a real grooming cost." },
  { slug: "mastiff", name: "Mastiff", group: "Working", size: 5, band: "moderate",
    aliases: ["english mastiff","old english mastiff","mastif","masstiff"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "At 80 kg-plus this is a Kennel Club Category Three breed carrying hip dysplasia, spinal weakness and gastric torsion risk. Keep the hour low-impact, keep it away from meals, and restrict growth-period exercise heavily." },
  { slug: "miniature-dachshund", name: "Miniature Dachshund", group: "Hound", size: 1, band: "low",
    aliases: ["mini dachshund","mini sausage dog","miniature dachsund","mini dachsund","mini doxie","mini daschund"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 30 minutes",
    note: "PDSA separates the varieties and gives the miniature 30 minutes, so the RKC hour is a ceiling rather than a target. The long back and short legs carry high disc-disease risk: no jumping, limit stairs, use ramps, and keep to flat steady lead walks." },
  { slug: "miniature-poodle", name: "Miniature Poodle", group: "Utility", size: 2, band: "moderate",
    aliases: ["mini poodle","min poodle","mini poodles"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: no size-specific figure",
    note: "PDSA publishes only one combined Poodle page, so the RKC hour is the primary figure and Purina’s one to two hours pushes to the top of this band. Extremely trainable, so scent games and training genuinely count towards the day." },
  { slug: "miniature-schnauzer", name: "Miniature Schnauzer", group: "Utility", size: 2, band: "moderate",
    aliases: ["mini schnauzer","min schnauzer","miniature snauzer","mini snauzer"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Treat this as the top of the moderate band — the authorities say an hour while Purina stretches to two. Terrier-style prey drive means recall work and secure running matter more than raw distance, and the breed’s pancreatitis risk makes weight control important." },
  { slug: "newfoundland", name: "Newfoundland", group: "Working", size: 5, band: "moderate",
    aliases: ["newfie","newf","newfoundland dog","newfy","newfoundlander"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "An hour, split into shorter sessions. The very heavy double coat and 50 kg-plus bulk make heat a serious problem — swim rather than walk in warm weather — and the long growth period plus joint disease risk demand strict puppy restriction." },
  { slug: "nova-scotia-duck-tolling-retriever", name: "Nova Scotia Duck Tolling Retriever", group: "Gundog", size: 3, band: "high",
    aliases: ["toller","tollers","duck toller","nova scotia retriever","tolling retriever"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: no page",
    note: "Sources conflict: the RKC says up to an hour while Purina UK talks about several hours. We have banded above the RKC tier deliberately, because under-walking a noisy, intense retrieve-and-water breed is the costlier mistake." },
  { slug: "old-english-sheepdog", name: "Old English Sheepdog", group: "Pastoral", size: 4, band: "working",
    aliases: ["oes","old english sheep dog","dulux dog","bobtail"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Reads as a placid family dog and is anything but — this is a drover breed and both authorities publish two hours or more. The dense coat means heat-limited summer walking and daily grooming, and the long growth period demands restricted puppy exercise." },
  { slug: "papillon", name: "Papillon", group: "Toy", size: 1, band: "low",
    aliases: ["papillion","pappillon","butterfly dog","phalene","pap"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "The published minimum is 30 minutes, but that under-sells the breed: Papillons are among the most trainable toy dogs and serious agility competitors, so trick training and brain work matter more here than walk length." },
  { slug: "parson-russell-terrier", name: "Parson Russell Terrier", group: "Terrier", size: 2, band: "high",
    aliases: ["parson","parson jack russell","parson russell","prt","parsons russell terrier","parson terrier"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Deliberately banded above the Jack Russell: this is the taller, square-built working fox terrier and both Purina and PDSA’s body copy stretch to one to two hours. Fitness-driven, so the fitter it gets the more it wants — a stamina and scent dog rather than a sprinter." },
  { slug: "patterdale-terrier", name: "Patterdale Terrier", group: "Terrier", size: 2, band: "high",
    aliases: ["patterdale","fell terrier","patterdale terrier dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: no breed page (not Kennel Club recognised); PDSA: no page",
    note: "A working fell type rather than a show breed, so there is no official tier and the evidence is Purina plus secondary UK guides. Extreme prey drive and near-inexhaustible stamina in a small frame: it needs secure enclosed space and real mental work, never just lead walking." },
  { slug: "pembroke-welsh-corgi", name: "Pembroke Welsh Corgi", group: "Pastoral", size: 2, band: "moderate",
    aliases: ["corgi","corgie","welsh corgi","pembroke corgi","pembroke","queens corgi","corgy"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour (generic Welsh Corgi page)",
    note: "RKC gives the Pembroke figure specifically and Purina agrees at an hour or more; note PDSA runs one combined Welsh Corgi page. The long back on short legs carries real disc risk, so keep to level ground and guard hard against weight gain." },
  { slug: "pointer", name: "Pointer", group: "Gundog", size: 4, band: "working",
    aliases: ["english pointer","pointers"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Two hours plus by all three sources, and Purina stresses free running rather than lead miles. Bred to gallop and cover ground; lightly built with a very short coat, so it feels cold and wet more than most large gundogs." },
  { slug: "pomeranian", name: "Pomeranian", group: "Toy", size: 1, band: "low",
    aliases: ["pom","poms","pom pom","teacup pom","teacup pomeranian","pomeranion","pomerainian","pommeranian"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "Both authorities give 30 minutes despite the lively reputation. The dense double coat makes them heat-intolerant, and tracheal collapse plus luxating patellas mean a harness rather than a collar." },
  { slug: "pug", name: "Pug", group: "Toy", size: 2, band: "low",
    aliases: ["pugs","pugg","black pug"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: Less than 1 hour",
    note: "Sources conflict on the ceiling, but we band low because this is a Kennel Club Category Three flat-faced breed with high airway and heatstroke risk. Short, frequent, cool-hours walks beat one long one, every time." },
  { slug: "rhodesian-ridgeback", name: "Rhodesian Ridgeback", group: "Hound", size: 4, band: "working",
    aliases: ["ridgeback","rhodesian ridge back","rhodesian","ridgey"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "PDSA calls them very high energy and asks for a minimum of two hours in several long walks with plenty of secure off-lead time, plus puzzle work. Large, powerful and slow to mature, so restrict distance and impact until the growth plates close." },
  { slug: "rottweiler", name: "Rottweiler", group: "Working", size: 5, band: "working",
    aliases: ["rottie","rotty","rott","rotweiler","rottweiller","rotwiler","rottweilier"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "Both authorities publish 120 minutes or more alongside structured training, which is far more than the breed’s couch-potato reputation suggests. Heavy and prone to hip, elbow and cruciate problems, so build distance gradually and restrict a growing puppy." },
  { slug: "rough-collie", name: "Rough Collie", group: "Pastoral", size: 4, band: "moderate",
    aliases: ["lassie dog","lassie","long haired collie","long-coated collie","scotch collie"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: no page",
    note: "Do not borrow the Border Collie’s two-hour figure — RKC and Purina both put this breed at roughly an hour. The heavy double coat limits summer walking, and MDR1 and Collie Eye Anomaly both occur here." },
  { slug: "saint-bernard", name: "Saint Bernard", group: "Working", size: 5, band: "moderate",
    aliases: ["st bernard","saint bernhard","st bernards","sain bernard"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "A Kennel Club Category Three breed where joint disease is common enough that PDSA explicitly says to cut below the one-hour baseline if the dog is affected. Heavy coated and heat-limited, with a long puppy restriction period." },
  { slug: "saluki", name: "Saluki", group: "Hound", size: 4, band: "working",
    aliases: ["persian greyhound","gazelle hound","saluki dog","saluqi"],
    brachycephalic: false, giantGrowth: false, sighthound: true,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "RKC and PDSA outrank Purina’s one to two hours here. An extreme long-distance sighthound needing safe galloping space rather than road miles; recall is effectively absent once chasing, and the fine coat means a coat in cold weather." },
  { slug: "samoyed", name: "Samoyed", group: "Pastoral", size: 4, band: "working",
    aliases: ["sammy","sammie","smiley dog","samoyd","sammy dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "RKC says more than two hours, PDSA sets a two-hour minimum, and RKC also flags it as a country breed wanting a large garden. Arctic sled heritage and a very thick coat make it markedly heat-intolerant, so British summer walks belong at either end of the day." },
  { slug: "scottish-terrier", name: "Scottish Terrier", group: "Terrier", size: 2, band: "moderate",
    aliases: ["scottie","scotty","scottie dog","scotch terrier","aberdeen terrier"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "A full hour despite the dumpy short-legged build — do not down-rate this one on appearance. The long back suits low-impact walking over jumping, and the breed carries Von Willebrand’s disease and a raised bladder cancer risk." },
  { slug: "shar-pei", name: "Shar Pei", group: "Utility", size: 3, band: "moderate",
    aliases: ["sharpei","shar-pei","chinese shar pei","shar pay","sharpay"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "All three sources publish about an hour a day. Heavy skin folds plus a shortened muzzle make this breed heat-intolerant and prone to fold infections, so keep walks cool and steady rather than fast." },
  { slug: "shetland-sheepdog", name: "Shetland Sheepdog", group: "Pastoral", size: 2, band: "moderate",
    aliases: ["sheltie","shelty","shetland collie","mini collie","miniature collie","shetland sheep dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "All three sources converge on about an hour, but this is an agility and obedience specialist so the hour should carry varied routes and training rather than one flat plod. Dense double coat makes hot-weather walks a genuine risk." },
  { slug: "shih-tzu", name: "Shih Tzu", group: "Utility", size: 1, band: "moderate",
    aliases: ["shitzu","shizu","shitzhu","shi tzu","shih-tzu"],
    brachycephalic: true, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "The published hour is best delivered as two or three 20-minute strolls, never one long walk — Purina notes the breed would rather have exactly that. Flat-faced and heat-intolerant, so cool hours only in summer." },
  { slug: "siberian-husky", name: "Siberian Husky", group: "Working", size: 4, band: "working",
    aliases: ["husky","huskie","sibe","siberian","siberian huskie","husky dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "A true endurance sled breed needing two hours or more of real work plus variety. Very high prey drive and famously poor recall mean most of that has to be on a long line or in a secure field, and the double coat makes British summers hard going." },
  { slug: "sprocker-spaniel", name: "Sprocker Spaniel", group: "Gundog (cross)", size: 3, band: "high",
    aliases: ["sprocker","springer cocker cross","springer x cocker","sprockers"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: not recognised (Springer x Cocker cross); PDSA: no page",
    note: "No official tier exists, so this sits between the Springer’s top tier and the Cocker’s one hour. Most UK sprockers come from working lines on both sides, so treat 60 to 90 minutes as the floor and a working-bred individual as a band higher." },
  { slug: "staffordshire-bull-terrier", name: "Staffordshire Bull Terrier", group: "Terrier", size: 3, band: "moderate",
    aliases: ["staffy","staffie","staff","sbt","staffy bull","staffordshire terrier","staford bull terrier"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "RKC and PDSA agree on about an hour, though Purina’s own summary tag contradicts its body copy with 120 minutes; we have followed the two authorities. Broad short muzzle means heat limits, and the enormous play and tug drive means quality beats raw distance." },
  { slug: "standard-dachshund", name: "Standard Dachshund", group: "Hound", size: 2, band: "moderate",
    aliases: ["dachshund","sausage dog","dachsund","dashund","doxie","weiner dog","standard dachsund","daschund","dachshound"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "PDSA and RKC both give the standard an hour, which outranks Purina’s 30-minute minimum. Same back risk as the miniature — no jumping, limit stairs, and go easy while a puppy is still developing." },
  { slug: "standard-poodle", name: "Standard Poodle", group: "Utility", size: 4, band: "high",
    aliases: ["poodle","poodles","std poodle"],
    brachycephalic: false, giantGrowth: true, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour (combined Poodle page)",
    note: "We band above the RKC tier because Purina puts it at one to two hours plus and this is a large water-retrieving gundog; note PDSA runs one combined Poodle page with Standard-sized weights. Large-breed joint and bloat risk means restricted puppy work and no running straight after food." },
  { slug: "standard-schnauzer", name: "Standard Schnauzer", group: "Utility", size: 3, band: "high",
    aliases: ["schnauzer","mittelschnauzer","snauzer"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Banded above the RKC tier because Purina says a couple of hours and this is the original working vermin and guard schnauzer. It strongly needs a job — without training and problem-solving the walk alone will not settle it." },
  { slug: "tibetan-terrier", name: "Tibetan Terrier", group: "Utility", size: 3, band: "moderate",
    aliases: ["tibetan terriers","tibetan"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "Not actually a terrier but a Tibetan herding and companion breed with broad snowshoe feet that handle rough ground and cold well. All three sources agree on about an hour; summer heat, not distance, is the limiting factor." },
  { slug: "toy-poodle", name: "Toy Poodle", group: "Utility", size: 1, band: "moderate",
    aliases: ["teacup poodle","toy poodles","tiny poodle"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: no size-specific figure",
    note: "RKC and Purina both give about an hour, ideally as two walks. Toy size brings patella luxation and tracheal collapse risk, so use a harness and discourage jumping off furniture." },
  { slug: "weimaraner", name: "Weimaraner", group: "Gundog", size: 4, band: "working",
    aliases: ["weim","weims","weimeraner","wiemaraner","grey ghost","weimaraner dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: More than 2 hours per day; PDSA: 2 hours",
    note: "RKC, PDSA and the UK breed club all converge on two hours of free running plus disciplined walking and mental work. Deep-chested and at real risk of bloat, so keep hard exercise well clear of mealtimes." },
  { slug: "west-highland-white-terrier", name: "West Highland White Terrier", group: "Terrier", size: 2, band: "moderate",
    aliases: ["westie","westy","west highland terrier","west highland white","highland terrier","westie dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "A full hour, which is more than the small frame suggests. Prone to atopic skin disease and to knee and hip problems, so steady varied walking beats repetitive high-impact ball chasing." },
  { slug: "whippet", name: "Whippet", group: "Hound", size: 3, band: "moderate",
    aliases: ["whipet","wippet","whipperd"],
    brachycephalic: false, giantGrowth: false, sighthound: true,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour",
    note: "All three sources agree on about 60 minutes, and PDSA suggests a short morning walk plus a longer sniffy one. A sighthound that wants short sprints in a secure area rather than distance; thin coat and almost no body fat means a coat in cold or wet weather." },
  { slug: "wire-fox-terrier", name: "Wire Fox Terrier", group: "Terrier", size: 2, band: "moderate",
    aliases: ["fox terrier","wire fox","wire haired fox terrier","wirehaired fox terrier","wire fox terrier dog"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 1 hour per day; PDSA: 1 hour (combined Fox Terrier page)",
    note: "RKC lists this as Fox Terrier (Wire) and PDSA does not split wire from smooth; both give an hour, with Purina stretching to two. Busy, mischievous and escape-prone, so a securely fenced space matters as much as the walk." },
  { slug: "working-cocker-spaniel", name: "Working Cocker Spaniel", group: "Gundog", size: 3, band: "working",
    aliases: ["working cocker","field cocker","worker cocker"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: no separate entry (RKC lists only Spaniel (Cocker)); PDSA: no separate entry",
    note: "Neither the RKC nor PDSA separates working from show lines, so the published cocker figure of one hour materially under-states this dog. Hunt and scent drive is enormous: walking alone will not settle one, so count scent work and retrieve drills towards the daily total." },
  { slug: "yorkshire-terrier", name: "Yorkshire Terrier", group: "Toy", size: 1, band: "low",
    aliases: ["yorkie","yorkies","yorky","york terrier","teacup yorkie","yorkshire terrior"],
    brachycephalic: false, giantGrowth: false, sighthound: false,
    source: "RKC: Up to 30 minutes per day; PDSA: 30 minutes",
    note: "Thirty minutes is a floor rather than a ceiling — Purina’s own quick facts note they will happily do one to two hours. A terrier brain in a toy body, but fragile bones plus tracheal collapse risk mean harness only and frequent short walks over one hard one." },
];
